name: weather
description: Flutter MIUI Weather.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  json_annotation: ^2.1.0
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2
  amap_location: ^0.2.0
  simple_permissions: ^0.1.9
  fluttertoast: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.1.1
  build_runner: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/main_circleindicator_located_city.png
    - images/main_circleindicator_located_city_s.png
    - images/main_circleindicator_city.png
    - images/main_circleindicator_city_s.png
    - images/bg_scrollview_middle_layer_overcast.png
    - images/2.0x/bg_scrollview_middle_layer_sunny.png
    - images/2.0x/icon_gray_bg_sunny.png
    - images/2.0x/sunny_bg_high_light.png
    - images/2.0x/sunny_bg_sun.png
    - images/2.0x/minute_rain_fall_heavy_rain.png
    - images/2.0x/realtime_aqi_skull.png
    - images/2.0x/realtime_aqi_leaf.png
    - images/2.0x/realtime_aqi_gas_mask.png
    - images/2.0x/minute_rain_fall_small_rain.png
    - images/2.0x/minute_rain_fall_normal.png
    - images/2.0x/minute_rain_fall_middle_rain.png

    - images/icon_cloudy.png
    - images/icon_cloudy_night.png
    - images/icon_fog.png
    - images/icon_gray_bg_cloudy.png
    - images/icon_gray_bg_cloudy_night.png
    - images/icon_gray_bg_fog.png
    - images/icon_gray_bg_heavy_rain.png
    - images/icon_gray_bg_heavy_snow.png
    - images/icon_gray_bg_ice_rain.png
    - images/icon_gray_bg_light_rain.png
    - images/icon_gray_bg_light_snow.png
    - images/icon_gray_bg_moderate_rain.png
    - images/icon_gray_bg_moderate_snow.png
    - images/icon_gray_bg_overcast.png
    - images/icon_gray_bg_pm_dirt.png
    - images/icon_gray_bg_rain_snow.png
    - images/icon_gray_bg_sand.png
    - images/icon_gray_bg_sunny.png
    - images/icon_gray_bg_sunny_night.png
    - images/icon_gray_bg_t_storm.png
    - images/icon_heavy_rain.png
    - images/icon_heavy_rain_press.png
    - images/icon_heavy_snow.png
    - images/icon_heavy_snow_press.png
    - images/icon_ice_rain.png
    - images/icon_light_rain.png
    - images/icon_light_rain_press.png
    - images/icon_light_snow.png
    - images/icon_moderate_rain.png
    - images/icon_moderate_snow.png
    - images/icon_overcast.png
    - images/icon_overcast_press.png
    - images/icon_pm_dirt.png
    - images/icon_rain_snow.png
    - images/icon_sand.png
    - images/icon_sand_press.png
    - images/icon_sunny.png
    - images/icon_sunny_night.png
    - images/icon_sunny_press.png
    - images/icon_t_storm.png

    - images/refresh_cloud_shape_0.png
    - images/refresh_cloud_shape_1.png
    - images/refresh_cloud_shape_2.png
    - images/refresh_cloud_shape_3.png
    - images/refresh_cloud_shape_4.png
    - images/refresh_cloud_shape_5.png
    - images/refresh_cloud_shape_6.png
    - images/refresh_cloud_shape_7.png
    - images/refresh_cloud_shape_8.png
    - images/refresh_cloud_shape_9.png
    - images/refresh_cloud_shape_10.png
    - images/refresh_cloud_shape_11.png
    - images/refresh_cloud_shape_12.png
    - images/refresh_cloud_shape_13.png
    - images/refresh_cloud_shape_14.png
    - images/refresh_cloud_shape_15.png

    - images/wind_east.png
    - images/wind_north.png
    - images/wind_northeast.png
    - images/wind_northwest.png
    - images/wind_south.png
    - images/wind_southeast.png
    - images/wind_southwest.png
    - images/wind_west.png

  fonts:
    - family: Temperature
      fonts:
        - asset: fonts/Big_Temperature.otf
    - family: Miui
      fonts:
        - asset: fonts/Miui-Thin.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
